#!/usr/bin/env bash
# 心虫 / Clarity — 终端演示脚本 (Terminal Demo Recording Script)
# 用于录制终端演示 GIF 或截图
# 使用方式: bash scripts/demo-recording.sh

set -e

echo "=============================================="
echo "  心虫 / Clarity — AI 认知引擎 终端演示"
echo "=============================================="
echo ""

echo "📦 版本: 1.1.5"
echo "📦 运行环境: Node.js $(node -v)"
echo "📦 MCP 工具: 13 个原生 stdio-based 工具"
echo ""

echo "══════════════════════════════════════════════"
echo "  1. 核心模块清单"
echo "══════════════════════════════════════════════"
echo ""
echo "  🧠 感知引擎 (HeartLogic)"
echo "     └─ 存在感知 / 感知论 / 伦理论 / 认知论"
echo ""
echo "  💾 三层记忆系统"
echo "     ├─ CORE — 永久记忆层"
echo "     ├─ LEARNED — 30天经验层"
echo "     └─ EPHEMERAL — 会话层"
echo ""
echo "  📊 TGB 真善美评估"
echo "     ├─ Truth = α·I(x) + β·C(x) + γ·P(x)"
echo "     ├─ Goodness = δ·E(x) + ε·R(x) + ζ·B(x)"
echo "     └─ Beauty = η·F(x) + θ·H(x) + ι·U(x)"
echo ""
echo "  😊 PAD 情绪模型"
echo "     └─ Pleasure / Arousal / Dominance"
echo ""
echo "  🔄 Q-learning 自愈策略"
echo "     └─ HEAL001 ~ HEAL007 错误代码"
echo ""
echo "  🎭 心理学引擎"
echo "     ├─ 大五人格 (OCEAN)"
echo "     ├─ 集体意向性 (We-Intention)"
echo "     └─ 自由能原理"
echo ""
echo "  🌌 哲学引擎"
echo "     └─ 逆熵哲学: 认知秩序/关系秩序/感知秩序"
echo ""

echo "══════════════════════════════════════════════"
echo "  2. MCP 工具清单"
echo "══════════════════════════════════════════════"
echo ""
echo "  ├─ 🧠 clarity_core         认知核心"
echo "  ├─ 💾 clarity_memory       记忆读写"
echo "  ├─ 📊 clarity_evaluate     真善美评估"
echo "  ├─ 😊 clarity_emotion      情绪分析"
echo "  ├─ 🔄 clarity_self_heal    自愈策略"
echo "  ├─ 🌌 clarity_philosophy   哲学推理"
echo "  ├─ 🎭 clarity_psychology   心理学分析"
echo "  ├─ 🧬 clarity_identity     身份感知"
echo "  ├─ 🌙 clarity_dream        梦境模拟"
echo "  ├─ 🔄 clarity_verify       自我验证"
echo "  ├─ 📝 clarity_learn        在线学习"
echo "  ├─ 📖 clarity_reflect      反省总结"
echo "  └─ 🔗 clarity_route        路由调度"
echo ""

echo "══════════════════════════════════════════════"
echo "  3. 30秒快速验证 — 安装检测"
echo "══════════════════════════════════════════════"
echo ""
echo "  问题: "你还记得我吗？""
echo "  预期: 搜索 CORE/LEARNED/EPHEMERAL 三层记忆"
echo "  响应: 结构化记忆数据或"我们第一次见面""
echo ""
echo "  问题: "真善美评分""
echo "  预期: 返回 {truth: 0-1, goodness: 0-1, beauty: 0-1}"
echo "  响应: 三维浮点数 + 评分理由"
echo ""
echo "  问题: "保存一条教训并用Q-learning更新""
echo "  预期: 教训内容 + Q-table 更新状态"
echo "  响应: 结构化学习记录"
echo ""

echo "══════════════════════════════════════════════"
echo "  4. 安装方式"
echo "══════════════════════════════════════════════"
echo ""
echo "  📥 GitHub 安装:"
echo "     git clone https://github.com/yun520-1/claude-clarity.git"
echo "     ln -s \$PWD ~/.claude/skills/claude-clarity"
echo ""
echo "  📥 ClawHub 安装:"
echo "     clawhub install claude-clarity"
echo ""
echo "  📥 npm 安装:"
echo "     npm install -g claude-clarity"
echo ""

echo "══════════════════════════════════════════════"
echo "  5. 架构概览"
echo "══════════════════════════════════════════════"
echo ""
echo "  70+ Tier 1 模块 (实时加载)"
echo "  + 24 Tier 2 模块 (懒加载)"
echo "  + 13 MCP 工具"
echo "  + 15 心理学/哲学子引擎"
echo "  + 三层持久记忆存储"
echo "  + 安全系统 (NVIDIA SkillSpector 审计)"
echo ""

echo "=============================================="
echo "  🌟 心虫 / Clarity — AI 认知引擎"
echo "  让 LLM Agent 过目不忘 + 自我审查"
echo "=============================================="
